package org.bxkr.transit.models

data class DateTravel(
    val arrivalStationHasWicket: Boolean,
    val arrivalStationId: Long,
    val arrivalStationLatinName: String,
    val arrivalStationName: String,
    val arrivalTime: String,
    val canceled: Any,
    val carriers: List<String>,
    val comfortOptionsSummary: List<Any>,
    val cost: Int,
    val defaultDirection: Boolean,
    val departureStationHasWicket: Boolean,
    val departureStationId: Long,
    val departureStationLatinName: String,
    val departureStationName: String,
    val departureTime: String,
    val deviation: Any,
    val finishStationId: Long,
    val finishStationLatinName: String,
    val finishStationName: String,
    val finishTime: String,
    val mcd: Int,
    val motionMode: String,
    val rzdTrainCategoryId: Int,
    val scheduleId: Long,
    val shortCarrier: String,
    val startStationId: Long,
    val startStationLatinName: String,
    val startStationName: String,
    val startTime: String,
    val tariffId: Long,
    val trainCategoryId: Int,
    val trainNumber: String
)